name: End-to-end tests

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install --force

    - name: Run npm start
      run: npm start &
      if: success()

    - name: Wait for application to start
      run: sleep 20s

    - name: Cypress run
      uses: cypress-io/github-action@v5.1
      with:
        record: true
        # Cancel the run after 2 failed tests
        auto-cancel-after-failures: 2
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
